# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('quic-stream', ['dash','quicdash', 'internet', 'wifi', 'buildings', 'applications', 'point-to-point', 'quic'])
    obj.source = 'quic-stream.cc'
